name: Android CI/CD

on:
  push:
    branches: [ main, 'Android-*' ]
    paths:
      - '.github/workflows/android_ci_cd.yml'
      - 'Mobile/**'
    tags:
      - 'v*'  # CD: 仅在打 tag（如 v1.0.0）时触发
  pull_request:
    branches: [ main ]
    paths:
      - 'Mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Mobile

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Android environment
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Add secrets to local.properties
        run: |
          echo "IP=${{ secrets.IP }}" >> local.properties
          echo "SecretId=${{ secrets.SECRET_ID }}" >> local.properties
          echo "SecretKey=${{ secrets.SECRET_KEY }}" >> local.properties

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        shell: bash
        run: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses || true

      - name: Install required SDK components
        shell: bash
        run: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          sdkmanager --install "platform-tools" "platforms;android-33"

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload APK to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Mobile/app/build/outputs/apk/debug/app-debug.apk
