name: Backend CI

on:
  push:
    branches: [ main ]
#    paths:
#      - 'smart-english-backend/**'
  pull_request:
    branches: [ main ]
#    paths:
#      - 'smart-english-backend/**'

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-english-backend  # 设置工作目录

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'  

      # 创建环境配置文件（根据项目需要）
      - name: Setup environment config
        run: |
          echo "Creating application.properties"
          touch src/main/resources/application.properties
          cat > src/main/resources/application.properties <<EOF
          ${{ secrets.APPLICATION_PROPERTIES }}
          EOF
          chmod 600 src/main/resources/application.properties

      # Maven依赖缓存（增强版）
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target/**  # 缓存构建输出
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 验证Maven配置
      - name: Validate Maven setup
        run: mvn --version

      # 构建并运行测试
      - name: Build and test with Maven
        run: mvn clean test -B -V -e
        # 参数说明:
        # -B: 批处理模式
        # -V: 显示版本
        # -e: 显示详细错误

